Bump deps in an attempt to fix sporadic failures on ci
ejgallego/coq-lsp pull request #135
Opened 2022-12-31 11:40 UTC by artagnon

2023-01-02 23:51 UTC, ejgallego requested changes
What are these sporadic failures?

Nack on the 4.14 part, 0.1.0 had a lower bound of 4.13 and that was a problem but quite a lot of users which are still bound to lower versions.

In general, I'm not a fan of restricting deps artificially, `coq-lsp` should aim to support all OCaml versions Coq supports unless there is a reason.

2023-01-03 08:19 UTC, artagnon commented
> What are these sporadic failures?
> 
> Nack on the 4.14 part, 0.1.0 had a lower bound of 4.13 and that was a problem but quite a lot of users which are still bound to lower versions.
> 
> In general, I'm not a fan of restricting deps artificially, `coq-lsp` should aim to support all OCaml versions Coq supports unless there is a reason.

Fixed now. The sporadic failures were seen on macos, but it didn't look like my patch helped in any way: looks like it was due to changes to macos runners on Github; anyway, it's fixed now.

2023-01-03 15:11 UTC, ejgallego commented on .github/workflows/build.yml
> +        run: opam exec -- make
Why this change? Relying on the default target seems fragile to me.

2023-01-03 15:11 UTC, ejgallego commented on coq-lsp.opam
> +  "dune"         { build & >= "3.6.1"  }
Why this change, in fact our minimal supported dune is 3.2, we use 3.5 only because of the vendoring.

2023-01-03 15:12 UTC, ejgallego commented on coq-lsp.opam
> +  "ppx_deriving_yojson" {           >= "3.7.0"    }
This is too restrictive for some users on older OCaml versions, they explicitly demanded we support them and a big users at Inria, so nack.

2023-01-03 15:12 UTC, ejgallego commented on coq-lsp.opam
> +]
This is wrong.

2023-01-03 15:12 UTC, ejgallego commented on editor/code/package.json
> +    "@types/node": "^18.11.18",
For now our minimal node version is 16, so we can bump to 16.

2023-01-03 15:13 UTC, ejgallego commented on editor/code/package.json
> +    "@types/vscode": "^1.74.0",
For now our base is 1.73, do we need 1.74 for some feature? Otherwise let's stay a 1.73.

Rest of changes are ok to me.

2023-01-03 15:14 UTC, closed without merging

2023-01-03 15:14 UTC, artagnon commented
Closing, as it's not worth re-rolling.