doc: fix terminator tokens
ejgallego/coq-lsp pull request #136
Opened 2023-01-02 10:05 UTC by artagnon

Add "end", and remove "..." and BULLET.

2023-01-02 13:55 UTC, Alizter commented
Why remove `...` and bullet?

2023-01-02 13:57 UTC, artagnon commented
Try `T2048.v` on `master` and this branch. The error recovery codepath is broken with `...` and bullet.

2023-01-03 11:21 UTC, Alizter commented
@ejgallego I would like to understand the role of terminator tokens. As it stands, my assumptions are anything we can consider terminating a Coq "sentence". This is why the removal of such tokens doesn't make sense to me. However, if the role of these tokens is otherwise, we should make that clear in the code.

2023-01-03 11:26 UTC, artagnon commented
The code is clear: we're just matching against the next token on `Gramlib.Stream`: `BULLET` isn't a terminator token because of `|-`, and I assume `...` isn't different from three consecutive `.` s; I've never seen a `...`, so I can't be sure.

2023-01-03 15:58 UTC, ejgallego commented
First, I see 3 quite different kind of changes in this PR, that makes review pretty hard, please submit one PR for each change.

The parsing recovery heuristic is just a heuristic, however I'm unsure I understand the problem here, in particular why to remove `...`, can we have a self-contained test-case?

2023-01-03 16:01 UTC, ejgallego commented
Actually seeing your comment about `|-` , I think you have been bitten by a different bug, which is Coq parser getting broken due to https://github.com/coq/coq/issues/12575

If you have coq-lsp loading in a file ssreflect, and then trying to parse a different file, you'll get plenty of errors.

Can you confirm the weird stuff happens after you restart the server with just one file open?

2023-01-03 17:56 UTC, artagnon commented
I've re-added `...`, but `BULLET` is problematic on `T2048.v`: I get syntax errors near `|-`.

2023-01-03 18:12 UTC, ejgallego commented
> I've re-added `...`, but `BULLET` is problematic on `T2048.v`: I get syntax errors near `|-`.

The file should check without errors, are you sure it is not the problem I mentioned above?

2023-01-03 18:47 UTC, artagnon commented
Yeah, it seems flaky; seemed to work better with my patch at the time of writing.

2023-01-03 18:49 UTC, ejgallego requested changes
I'm afraid the issue that @artagnon has seen is orthogonal to this patch.

Files failing to parse properly is due to some yet unsolved bug with coq-lsp or Coq management of the parsing state.

`Tok.BULLET` is a valid (and worthwhile) parsing recovery point and should not be removed from the heuristic.

2023-01-03 18:51 UTC, ejgallego commented
In particular @artagnon parsing will go mad when coq-lsp loads the ssreflect plugin in some other buffer, but the bug is general.

2023-01-03 18:53 UTC, closed without merging

2023-01-03 18:53 UTC, ejgallego commented
> Yeah, it seems flaky; seemed to work better with my patch at the time of writing.

Restarting `coq-lsp` usually solves this if you don't load the ssreflect plugin (or any other syntax heavy plugin) first. So it seems that the problem is solved with the patch, but that codepath is never reached in the first place.

2023-01-03 18:59 UTC, ejgallego commented
That bug is actually driving me crazy, I can reproduce reliably by loading `ex0.v` and then `RTrigo`.

Maybe `Print Grammar` will show what the problem is?

2023-01-03 19:00 UTC, artagnon commented
Does this patch help?

2023-01-03 19:10 UTC, artagnon commented
Nack, it doesn't. I just checked.

2023-01-03 19:18 UTC, ejgallego commented
See https://github.com/coq/coq/issues/12575#issuecomment-1370135265 , somehow sometimes keywords disappear and that's what causes the problem, in particular you say that `|-` not being a keyword, the mess was giant.