add version string in separate file and update version
ejgallego/coq-lsp pull request #162
Opened 2023-01-09 13:52 UTC by Alizter

This should make it easier to update the version when doing a release.

Signed-off-by: Ali Caglayan <alizter@gmail.com>

2023-01-09 14:59 UTC, ejgallego requested changes
Looks good to me, but:
- version is 0.1.3
- you need to update check_client_version too

2023-01-09 14:59 UTC, ejgallego commented on controller/version.mli
> +(* Written by: Emilio J. Gallego Arias                                  *)
You can remove the second part of this header I think.

2023-01-09 15:40 UTC, Alizter commented
@ejgallego I've updated check_client_version to use this now. I have also made the version API richer.

2023-01-09 15:50 UTC, ejgallego commented on controller/version.ml
> +    | x -> x)
That seems pretty over engineered to me, moreover, I don't want to maintain this code here, I'd rather use `semver2` if we ever have a need.

Let's keep things simple for now.

2023-01-09 15:51 UTC, ejgallego commented on controller/version.mli
> +val compare : t -> t -> [ `Equal | `Less | `More ]
Please don't use variants for use cases where they are not required (as discussed in the Dune context)

2023-01-10 12:47 UTC, ejgallego commented on controller/coq_lsp.ml
> +  if Version.equal (Version.of_string version) Version.current then ()
PR looks good to me thanks, tho I'm unsure if this whole dance `of_ / to_` is worth it.

If I was reading this, I'd be confused about the semantics of `Version.equal`, IMVHO older code was more explicit.

2023-01-10 12:49 UTC, ejgallego reviewed
Another point is that maybe the version file should be auto-generated (from `package.json`?) but that leads to modularity issues.

Ummm, proper setup is too complex for us, because it would consist of 3 packages: `protocol` / `client` / `server`

2023-01-10 22:19 UTC, ejgallego approved these changes

2023-01-10 22:25 UTC, merged