Fix typo in -impredicative-set parsing
ejgallego/coq-lsp pull request #241
Opened 2023-01-25 12:32 UTC by artagnon

2023-01-25 20:19 UTC, ejgallego commented on controller/coq_lsp.ml
> -    (* XXX what's the error code here *)
Actually that's a real TODO, `-32600` is likely not the right code.

Why do we mix unrelated changes in PRs?

2023-01-25 20:19 UTC, ejgallego requested changes
Thanks a lot for the fix, however the unrelated change needs to be removed (or an issue opened) as it is a real TODO.

2023-01-25 20:20 UTC, ejgallego commented
I guess a changelog would be also useful, users may wonder why it was not working before.

2023-01-25 20:21 UTC, ejgallego commented
Also we could add an entry for this in `examples` (or tests very soon I hope!)

2023-01-26 10:42 UTC, artagnon commented
We can't add an example, as it requires a `_CoqProject` to be at the root of the repository.

2023-01-26 15:39 UTC, ejgallego approved these changes

2023-01-26 15:41 UTC, ejgallego commented
> We can't add an example, as it requires a `_CoqProject` to be at the root of the repository.

I guess we can add subdirs in `example`, let's discuss about this in person as it is really related to #15

2023-01-26 15:41 UTC, merged