doc: Detail Nix usage in README.md
ejgallego/coq-lsp pull request #85
Opened 2022-11-28 13:43 UTC by Alizter

2022-12-26 23:33 UTC, ejgallego approved these changes

2022-12-26 23:34 UTC, ejgallego requested changes
On a second read, this seems to go in the wrong section. Please move to `Development`

2022-12-30 16:38 UTC, Alizter commented
@ejgallego Moved to appropriate place.

2023-01-03 00:07 UTC, ejgallego approved these changes
Thanks!

2023-01-03 00:15 UTC, merged